version: "3"
services:
  db:
    image: "postgres:13"
    container_name: "test_postgres"
    environment:
      POSTGRES_PASSWORD: "test"
    ports:
      - "5432:5432"
    volumes:
      - test_dbdata:/var/lib/postgresql/data
volumes:
  test_dbdata: